name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Vet and lint
      run: |
        go vet ./...
        go fmt ./...
        cd cmd/tblconv
        go vet ./...
        go fmt ./...

    - name: Test
      run: go test -race -cover -v ./...

    - name: Build cmd
      run: |
        cd cmd/tblconv
        go build -v ./...
